### ISSUE TITLE
这个方法也失效了吗？

### ISSUE THREAD

**Issue by JagoWang** [davideuler/youdao-wordlist-alfredworkflow#1]
![WX20190726-183454](https://user-images.githubusercontent.com/1396829/61946038-1f9fba80-afd4-11e9-91ab-7ceff047c8ae.png)

生词本还是添加失败。

**Comment by davideuler** [comment]
更新了一个版本， 目前还可以使用，如果是 MacOS 11/12 的新系统，使用新版本可以使用
